[package]
name = "minecraft-net-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"  # For parsing Rust code
quote = "1.0" # For generating Rust code
proc-macro2 = "1.0" # Backend for token streams